version: "3.9"

networks:
  graphx-network:
    driver: bridge

services:

  db:
    container_name: database
    build: ./database
    # image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passw
      POSTGRES_DB: main_database
    networks:
      - graphx-network
    ports:
      - '5438:5432'



  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.15
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - graphx-network
    restart: unless-stopped
    logging:
      driver: "none"




  spark-graphx:
    container_name: spark-graphx
    build:
      context: ./spark-graphx
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-graphx
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_ENV=PROD
    ports:
      - '8082:8080'
      - '7077:7077'
    networks:
      - graphx-network
    volumes:
      - ${HOME}/graph/logs/spark-graphx:/opt/spark-graphx/logs
