#!/bin/zsh

chmod +x ./spark-graphx/generateJAR

mkdir ./spark-graphx/driver-jars
num_jars=$(ls -la ./spark-graphx/driver-jars | wc -l)

if [[ $num_jars -lt 4 ]]; then
  echo "Downloading postgresql JAR"
  cd ./spark-graphx/driver-jars
  curl -O https://jdbc.postgresql.org/download/postgresql-42.3.3.jar
  # wget for example in bash terminal
  cd ../..
fi

do_not_build=false

for arr in $@ ; do

  if [[ $arr = "--restart" ]] ; then
    echo "Restarting GraphX App."
    echo "Removing Docker container."
    docker stop spark-graphx
    docker rm -v spark-graphx
    docker rmi graph_spark-graphx
  fi

  if [[ $arr = "--do-not-build" ]] ; then
    do_not_build=true
  fi

done

if [[ $do_not_build = false ]] ; then
  echo "Removing Binaries."
  rm -rf ./spark-graphx/target/scala-2.12/
  ./spark-graphx/generateJAR
  rm -rf $HOME/graph/logs/application.log
fi


docker-compose up -d # --build
